### ISSUE TITLE
Add note that the app can impose its own timeout value

### ISSUE THREAD

**Issue by juberti** [cdh4u/draft-ice-pac#10]
If things are taking too long, it can try an ICE restart at any point.

**Comment by cdh4u** [comment]
Yes. It's probably good to explicitly say that if no peer reflexive candidates arrive within time X, the agent will declare ICE failure according to normal 8445 procedures.

**Comment by juberti** [comment]
My point here was that the application, not the ICE agent, could set its own timeout if it wants to fail faster than the connectivity check transaction timeout.

**Comment by cdh4u** [comment]
I guess it depends on the API exposed by the ICE agent what the application can do, but I agree it would be good to recommend that an application is able to set the value.
