### ISSUE TITLE
When does the timer start?

### ISSUE THREAD

**Issue by juberti** [cdh4u/draft-ice-pac#12]
The "alternative c)" that I proposed is to "Start the timer as soon as we have received a remote offer or answer and have also sent a local candidate to the remote side".

The rationale for this is:
A) we can't start ICE processing (checks) until we get a remote offer/answer with ICE credentials
B) we can't receive an incoming check that could create a prflx candidate unless we sent a candidate to the remote side

**Comment by cdh4u** [comment]
Based on your suggestion, I don't think we need to talk about when we have received a remote offer or answer. We only need to talk about when we have SENT a local candidate to the remote side.

**Comment by juberti** [comment]
Not sure I agree with this, because we can't start ICE processing until we have the remote ICE credentials.

**Comment by nils-ohlmeier** [comment]
I agree that requiring to only start the timer when a remote SDP is available and local candidates have been handed out seems the safest combination to choose.

**Comment by cdh4u** [comment]
I agree - my mistake.

**Comment by pthatcherg** [comment]
I agree with Justin's proposed rule, but I'd just point out that 8445 does not reference SDP except as an example, so the rule might need to be formulated with something like "start the timer once remote candidate information has been received, local candidate information has been sent, and at least one local candidate has been sent".

**Comment by juberti** [comment]
I tried to capture that notion in
https://github.com/cdh4u/draft-ice-pac/pull/15.

**Comment by juberti** [comment]
When writing up this text, I realized there are edge cases where you might want to discover prflx candidates even if you didn't send any candidates (e.g., you don't send any candidates, you get a single candidate (with IP1) from the remote side, and when you check it, you get a response back from IP2).

Ergo, I think we should start the timer as soon as we have local and remote ICE credentials, regardless of whether or not we send a candidate. See #15 for the latest wording.

**Comment by pthatcherg** [comment]
I like the new wording and approved #15

**Comment by cdh4u** [comment]
There is an e-mail thread about this on the ICE WG list, so I suggest we continue the discussion there:

https://mailarchive.ietf.org/arch/msg/ice/hh__ZusU0uOE2XMw9JwXZRYBpcM

**Comment by juberti** [comment]
I think it would be easiest to discuss the issue internally here. If we need to involve other WG members we can take it to the list, but so far others seem to agree with my conclusions.

**Comment by cdh4u** [comment]
I am not saying I disagree - I just can't map what is being discussed with the proposed text, and that is what I am trying to clarify.
