### ISSUE TITLE
How long does the timer run?

### ISSUE THREAD

**Issue by juberti** [cdh4u/draft-ice-pac#13]
I agree we should use the "max duration of a connectivity check transaction".

I think this value will work just fine in real world scenarios. And if the timer expires before we have tested all pairs (this can certainly happen, in the case of two hosts with no connectivity to each other), we just resume existing ICE processing, and fail when everything moves to the failed state (i.e., every pair has timed out). The timer is simply there to prevent premature failures.

**Comment by cdh4u** [comment]
Sounds good.
