### ISSUE TITLE
Add MUST-level requirements

### ISSUE THREAD

**Issue by juberti** [cdh4u/draft-ice-pac#9]
> 
> > 5.  The current draft says "MUST wait for" and "N SHOULD be X".  But together, that amounts to "SHOULD wait for X", so the whole
> > RFC ends up being a big SHOULD.  Is that normal for an RFC to only have SHOULDs and not MUSTs?  Seems less meaningful because
> 
> This is a reasonable point. We could say that the implementation MUST wait for enough time to receive peer-reflexive candidates. This value SHOULD be the local connectivity check timeout.

**Comment by cdh4u** [comment]
I agree that the text needs to be modified, but I now remember that we were requested to add a little more text regarding the timeout. 

As I said earlier, depending on the number of streams, how the candidates are prioritised etc, it might take a while before a candidate pair is tested to begin with. So, I think we could say that the timeout value is based on local policy, and that agents should take the number of streams and candidates into consideration when deciding on the timeout. We can then RECOMMEND a value of the local connectivity check timeout.

**Comment by juberti** [comment]
Peter's point in the original comment is that we should have some MUST-level requirement, e.g. that the agent MUST wait, and SHOULD wait for X seconds.

**Comment by cdh4u** [comment]
Yes, and I agree with Peter's point - sorry if I didn't make that clear. My point was that I think we need a little more text regarding the chosen value (X seconds).
